# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='chat_type',
            field=models.CharField(choices=[(b'Group Chat', b'Group Chat'), (b'Individual Chat', b'Individual Chat')], default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
