# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_log_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='chat_type',
            field=models.CharField(choices=[(b'Group Chat', b'Group Chat'), (b'Individual Chat', b'Individual Chat')], max_length=17),
        ),
    ]
