# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_auto_20170405_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(),
        ),
    ]
