# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_auto_20170405_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='log',
            name='modified_by',
        ),
    ]
