# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_auto_20170406_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rapidpro_status',
            field=models.BooleanField(default=False),
        ),
    ]
